package com.mycompany.poly.app.ui;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {
    private StudenManagementPanel mStudentPanel;
    private GPAManagementPanel mGPAPanel;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        tbrLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        qlsv = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        qld = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        tbrAboutUs = new javax.swing.JButton();
        tplMainBoard = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnFile_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuManageStudent = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuManageGPA = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuAboutUs = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        tbrLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/poly/app/icons/logout-icon-32.png"))); // NOI18N
        tbrLogout.setText("Đăng Xuất");
        tbrLogout.setFocusable(false);
        tbrLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrLogout);
        jToolBar1.add(jSeparator1);

        qlsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/poly/app/icons/10207-man-student-light-skin-tone-icon-32.png"))); // NOI18N
        qlsv.setText("Quản Lý Sinh Viên");
        qlsv.setFocusable(false);
        qlsv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        qlsv.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        qlsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlsvActionPerformed(evt);
            }
        });
        jToolBar1.add(qlsv);
        jToolBar1.add(jSeparator6);

        qld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/poly/app/icons/gpa-icon-32.png"))); // NOI18N
        qld.setText("Quản Lý Điểm");
        qld.setFocusable(false);
        qld.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        qld.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        qld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qldActionPerformed(evt);
            }
        });
        jToolBar1.add(qld);
        jToolBar1.add(jSeparator2);

        tbrAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/poly/app/icons/Actions-help-about-icon-32.png"))); // NOI18N
        tbrAboutUs.setText("Giới Thiệu");
        tbrAboutUs.setFocusable(false);
        tbrAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrAboutUs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrAboutUsActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrAboutUs);

        jMenu1.setText("Hệ Thống");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/poly/app/icons/logout-icon-16.png"))); // NOI18N
        jMenuItem1.setText("Đăng Xuất");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator3);

        mnFile_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnFile_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/poly/app/icons/Button-Close-icon-16.png"))); // NOI18N
        mnFile_Exit.setText("Thoát");
        mnFile_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFile_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnFile_Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");

        mnuManageStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuManageStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/poly/app/icons/10207-man-student-light-skin-tone-icon-16.png"))); // NOI18N
        mnuManageStudent.setText("Quản Lý Sinh Viên");
        mnuManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageStudentActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManageStudent);
        jMenu2.add(jSeparator4);

        mnuManageGPA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/poly/app/icons/gpa-icon.png"))); // NOI18N
        mnuManageGPA.setText("Quản Lý Điểm");
        mnuManageGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageGPAActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManageGPA);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Trợ giúp");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/poly/app/icons/Help-icon-16.png"))); // NOI18N
        jMenuItem6.setText("Nội Dung");
        jMenu5.add(jMenuItem6);
        jMenu5.add(jSeparator5);

        mnuAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/poly/app/icons/Actions-help-about-icon-16.png"))); // NOI18N
        mnuAboutUs.setText("Giới Thiệu");
        mnuAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutUsActionPerformed(evt);
            }
        });
        jMenu5.add(mnuAboutUs);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
            .addComponent(tplMainBoard)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tplMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnFile_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFile_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnFile_ExitActionPerformed

    private void mnuAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutUsActionPerformed
        tbrAboutUsActionPerformed(evt);
    }//GEN-LAST:event_mnuAboutUsActionPerformed

    private void mnuManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageStudentActionPerformed
        if(mStudentPanel == null){
            mStudentPanel = new StudenManagementPanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/com/mycompany/poly/app/icons/10207-man-student-light-skin-tone-icon-16.png"));
            tplMainBoard.addTab("Quản Lý Sinh Viên", icon, mStudentPanel, "Quản Lý Sinh Viên");
        }
        tplMainBoard.setSelectedComponent(mStudentPanel);
    }//GEN-LAST:event_mnuManageStudentActionPerformed

    private void mnuManageGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageGPAActionPerformed
        if(mGPAPanel==null){
            mGPAPanel = new GPAManagementPanel();
            ImageIcon icon = new ImageIcon(getClass()
                .getResource("/com/mycompany/poly/app/icons/gpa-icon.png"));
            tplMainBoard.addTab("Quản Lý Điểm", icon, mGPAPanel, "Quản Lý Điểm");
        }
        tplMainBoard.setSelectedComponent(mGPAPanel);
    }//GEN-LAST:event_mnuManageGPAActionPerformed

    private void tbrAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrAboutUsActionPerformed
        AboutUsDialog aboutDialog = new AboutUsDialog(this, true);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_tbrAboutUsActionPerformed

    private void tbrLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrLogoutActionPerformed
        Login Login = new Login(this, true);
        Login.setVisible(true);
    }//GEN-LAST:event_tbrLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Login login = new Login(this, true);
        login.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void qlsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlsvActionPerformed
        if(mStudentPanel == null){
            mStudentPanel = new StudenManagementPanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/com/mycompany/poly/app/icons/10207-man-student-light-skin-tone-icon-16.png"));
            tplMainBoard.addTab("Quản Lý Sinh Viên", icon, mStudentPanel, "Quản Lý Sinh Viên");
        }
        tplMainBoard.setSelectedComponent(mStudentPanel);
    }//GEN-LAST:event_qlsvActionPerformed

    private void qldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qldActionPerformed
        if(mGPAPanel==null){
            mGPAPanel = new GPAManagementPanel();
            ImageIcon icon = new ImageIcon(getClass()
                .getResource("/com/mycompany/poly/app/icons/gpa-icon.png"));
            tplMainBoard.addTab("Quản Lý Điểm", icon, mGPAPanel, "Quản Lý Điểm");
        }
        tplMainBoard.setSelectedComponent(mGPAPanel);
    }//GEN-LAST:event_qldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnFile_Exit;
    private javax.swing.JMenuItem mnuAboutUs;
    private javax.swing.JMenuItem mnuManageGPA;
    private javax.swing.JMenuItem mnuManageStudent;
    private javax.swing.JButton qld;
    private javax.swing.JButton qlsv;
    private javax.swing.JButton tbrAboutUs;
    private javax.swing.JButton tbrLogout;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
}
